spring:
  servlet:
  profiles:
    active:
      on-profiles: aws
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cpakosvi0vz2.ap-northeast-1.rds.amazonaws.com:3306/innodb
    username: taegon
    password: xorhs1998

  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug